Make OnValueChanged work with custom Serializable types
v0lt13/EditorAttributes pull request #19
Opened 2024-11-10 18:34 UTC by ArtemPindrus

Fixes the #18 issue.

Currently it's assumed that property.serializedObject.targetObject always returns an object containing the function passed to the OnValueChangedAttribute by name, but it can be an object "above". 
Like in the following example property.serializedObject.targetObject  returns instance of SerializeCustomSerializable, instead of instance of CustomSerializable that contains target function:
```csharp
using System;
using EditorAttributes;
using UnityEngine;

[Serializable]
public class CustomSerializable {
    [SerializeField]
    [OnValueChanged(nameof(OnValue))]
    private float s;

    private void OnValue() {
        Debug.Log("Changed!");
    }
}

public class SerializeCustomSerializable : MonoBehaviour {
    [SerializeField] private CustomSerializable cs;
}
```

I used property.propertyPath to trace the target object. Not sure whether it's the most appropriate way to do this.

2024-11-10 19:05 UTC, ArtemPindrus commented
Found another related problem:
```csharp
using System;
using EditorAttributes;
using UnityEngine;

[Serializable]
public class CustomSerializable {
    [SerializeField]
    [OnValueChanged(nameof(OnValue))]
    private float s;

    private void OnValue() {
        Debug.Log("Changed!");
    }
}

public class SerializeCustomSerializable : MonoBehaviour {
    [SerializeField] private CustomSerializable cs;
    
    private void OnValue() {
        Debug.Log("Changed!");
    }
}
```

Using the example above, ReflectionUtility.FindFunction(onValueChangedAttribute.FunctionName, property); will find OnValue() function of SerializeCustomSerializable, which is obviously not expected.

The [3bf5d08](https://github.com/v0lt13/EditorAttributes/pull/19/commits/3bf5d08cbe000472e7d4154a590e00a3e3bb846d) commit fixes the problem.

2024-11-11 00:55 UTC, v0lt13 requested changes
From what it seems, your function does basically the same thing that the ReflectionUtility.GetNestedObjectType does, so undo your changes on the ReflectionUtility script and use the already existing function which outputs the target object needed for the on value change attribute to work inside nested objects.

2024-11-12 13:33 UTC, v0lt13 requested changes
There is also no need to modify the FindFunction method since it was already handling nested objects in that if statement, the issue was only the attribute target

2024-11-13 14:29 UTC, v0lt13 approved these changes

2024-11-13 14:29 UTC, merged